### ISSUE TITLE
21.11/psi4:

### ISSUE THREAD

**Issue by markuskowa** [markuskowa/NixOS-QChem#128]
Psi4 fails to build on the 21.11 branch. It attempts to pull `QCElemental` from an external source:
```
-- Suitable qcelemental could not be located, Building qcelemental instead.
```
...
```
-- Using src='https://github.com/MolSSI/QCElemental/archive/v0.24.0.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
```

It seems that 23.0, which is in `nixpkgs` is too old for `Psi4-1.5`
@sheepforce should we downgrade Psi4 for NixOS-QChem-21.11 or back port QCElemental 24.0 to nixpkgs-21.11 (maybe the latter one)?

**Comment by sheepforce** [comment]
Yes, it is too old unfortunately and strictly requires 0.24.0. I would rather backport QCElemental to 21.11, as Psi4 1.5 had important bug fixes, that are influencing correctness of results.
