### ISSUE TITLE
Workaround for Python `packageOverrides`

### ISSUE THREAD

**Issue by mcwitt** [markuskowa/NixOS-QChem#183]
Thanks so much for this project! I've found it useful and have learned a lot from studying how it's organized.

I'm running into an issue that when I need to override packages in the `qchem.pkgs.python3` set, the overrides already applied by the overlay ([here](https://github.com/markuskowa/NixOS-QChem/blob/aff5d92a402dbb6fd72412dd93d2330c7a5e8b6b/overlay.nix#L287)) are apparently wiped out.

For example, I'd like to do something like the following:

```nix
{
  python3 = pkgs.qchem.python3.override {
    packageOverrides = prev: _: {
      mypackage = prev.buildPythonPackage {
        # …
      };
    };
  };

  pythonEnv = python3.withPkgs (ps: [ ps.mypackage ps.openmm ]);

  # …
}
```

But this fails with `error: attribute 'openmm' missing`.

I think this is related to the long-standing issue in nixpkgs: https://github.com/NixOS/nixpkgs/issues/44426

One of the [workarounds](https://github.com/NixOS/nixpkgs/issues/44426#issuecomment-410428253) mentioned in that issue is for overlays to expose `pythonOverrides` directly so that multiple overrides can be composed downstream using `lib.composeExtensions`. I wonder if you'd consider a PR exposing this in the overlay, or know of a different workaround?

**Comment by sheepforce** [comment]
I've tried getting it done without the `lib.composeExtension` by using `pythonPackages.nix` again but it lead nowhere. My attempt feels complicated and leads to infinite recursions:

```nix
let pythonOverrides = subset: cfg: qfinal: qprev:
      let qchemPythonOverrides = import ./pythonPackages.nix subset cfg qfinal qprev;
          myPythonOverrides = qprev.qchem.python3.pkgs.override { packageOverrides = pfinal: pprev: {
            openmm = pprev.openmm.override { enableCuda = true; };
          };};
       in myPythonOverrides;
    testOvl = final: prev: pythonOverrides prev.qchem { } final prev;
    qchemOvl = import ./overlay.nix;
    nixpkgs = import <nixpkgs>;
in  nixpkgs {
  overlays = [ qchemOvl testOvl ];
}
```

https://github.com/NixOS/nixpkgs/issues/44426 is very unfortunate and the arguments `pythonPackages.nix` requires makes it indeed difficult to use it as an overlay separately. I also have no better idea than exposing the partially applied python overlay function.

**Comment by sheepforce** [comment]
Nevermind, the code above is obviously nonsense, I am not even using `qchemPythonOverrides` in there. This however works;

```nix
let
  # The original overlay function that NixOS-QChem is using to modify the python packages.
  qchemPythonOverlay = import ./pythonPackages.nix ;

  # Your own python overlay to add and modify python packages.
  # E.g. unconditionally enable CUDA in OpenMM
  myPythonOverlay = final: prev: {
    openmm = prev.openmm.override { enableCuda = true; };
  };

  # The complete NixOS-QChem overlay itself, not just the python part.
  qchemOvl = import ./overlay.nix;

  # Combine the python overrides from NixOS-QChem with your own
  combinedPythonOvl = final: prev: {
    qchem.python3 = prev.python3.override { 
      packageOverrides = prev.lib.composeExtensions 
        (qPythonOverlay "qchem" (import ./cfg.nix) final prev) 
        myPythonOverlay;
    };
  };

# Apply NixOS-QChem and then the final version of the Python overlay
in import <nixpkgs> {
  overlays = [
    (import ./overlay.nix)
    combinedPythonOvl
  ];
}
```

**Comment by mcwitt** [comment]
@sheepforce thanks for looking into this! Your solution makes sense to me, but I think I've just stumbled upon an even simpler that seems to work for my use case (I might be missing some subtlety, though).

I didn't realize this before, but if passed a function instead of an attrset `override`, will pass in the existing overrides. Something like this is working for me:

```nix
{
  # …
  myPackageOverrides = prev: _: {
    mypackage = prev.buildPythonPackage {
      # …
    };
  };

  python3 = pkgs.qchem.python3.override (old: {
    packageOverrides = lib.composeExtensions old.packageOverrides myPackageOverrides;
  });

  pythonEnv = python3.withPkgs (ps: [ ps.mypackage ps.openmm ]);
  # …
}
```

I think there may still be an issue with passing multiple overlays to `nixpkgs` (which it looks like your example solves). I've noticed some other projects (e.g. https://github.com/tweag/jupyterWith/blob/93f75799b527b03de9acc09ae18cc4b8817fb0c5/nix/python-overlay.nix#L97-L102) compose `packageOverrides`. I wonder if a change like [this](https://github.com/mcwitt/NixOS-QChem/commit/7d3ca93c4632eea1939a17c7591c308cb60e30c9) would be useful here?

**Comment by sheepforce** [comment]
I am surprised that `python3.override` uses this `old:` pattern, but as it seems to work, I think your solution and similarly the one of `jupyterWith` is the best candidate so far. So yes, I think we should use it. @markuskowa do you agree?

**Comment by sheepforce** [comment]
@mcwitt your solutions you've linked looks nice, would you open the PR and possibly include an example in the PR, that shows that it works as intenden? :slightly_smiling_face:

**Comment by sheepforce** [comment]
The pythonOverlay is now at least available in the flake, as of [a386e4](https://github.com/markuskowa/NixOS-QChem/commit/a386e4322e6153ecbcc51cbd6605b77eb558fef1)
