### ISSUE TITLE
Fix fallout from gcc/gfortran-10 update

### ISSUE THREAD

**Issue by markuskowa** [markuskowa/NixOS-QChem#186]
The latest update of gcc and gfortran to version 10 caused some packages to break due to stricter code checking:

* [x] bagel https://github.com/markuskowa/NixOS-QChem/pull/185
* [x] amd-scalapack
* [x] exatensor
* [x] dirac https://github.com/markuskowa/NixOS-QChem/pull/190
* [x] iboview  (probably needs a C++ patch to be gcc-10 compatible)
* [ ] molpro-ext (should be updated probably)
* [x] mcdth
* [x] mesa-qc https://github.com/markuskowa/NixOS-QChem/pull/188
* [x] molcas-18.09
* [x] molden (7.1 may solve the problems, direct fix: https://github.com/NixOS/nixpkgs/pull/172348)
* [x] orient
* [x] pegamoid
* [x] siesta  (upstream nixpkgs), see https://github.com/NixOS/nixpkgs/pull/172182
* [x] wfoverlap

See also [Porting to GCC 10](https://gcc.gnu.org/gcc-10/porting_to.html).

**Comment by sheepforce** [comment]
I am currently a little bit short on time, but will try to fix mine as soon as I find a free time slot.

**Comment by sheepforce** [comment]
I've tried also fixing Molden. The issue would probably simply be solved by switching to Molden7.0. Unfortunately fetchurl and curl in general refuse connecting to the site due to some SSL certificate errors. Also had no success with just switching to http there.

**Comment by markuskowa** [comment]
Molden may require more work. I have tried to update it several times, but ran into a variety of issues (changes in the build system, segfaults in the final binary).
Molden 7.1 is now available (put online two days ago). I will give it another try.

**Comment by markuskowa** [comment]
Lesson learned: some fixes broke the build against gfortran-9, but updating the nixpkgs pinning of course broke the rest that wasn't yet fixed. In the future, I will make a staging branch for such "major breakage" situations. PRs will then go on the staging branch first until everything is fixed. This will guarantee that we have a fully "green" master at all times.
