### ISSUE TITLE
Porting to nixpkgs main repository

### ISSUE THREAD

**Issue by costrouc** [markuskowa/NixOS-QChem#2]
These derivations looks like great contributions to the nixpkgs repository. I know that you are very knowledgeable on building these scientific codes with nix since you helped me with quantum-espresso. Any reason that these have not been ported to the main repository?

**Comment by markuskowa** [comment]
For some reason I do not get notified automatically here. Sorry for the late reply.
I set this repository up as an overlay for derivations that work for me, but are not yet upstream quality or  may not be of interest for enough people. Some derivations are just copies of upstream derivations with my own optimization.

However, I do plan to post most of them upstream piece by piece after I can confirm that they actually run well (some of them are already in nixpkgs). Some of these packages come with a rather non-standard build system and require a bit more work to build them successfully. From my experience, "it builds", does not always mean it also runs well. Having them thoroughly tested here hopefully helps to increase the quality. 

Feel free to pick what you need from this repository or to ask me about the status of certain derivations.
It is nice to see that there are more people in the Nix community interested in scientific computing/HPC related topics. Let's make NixOS the OS of choice for compute cluster environments :tada: !

**Comment by costrouc** [comment]
Completely agree that I want to make NixOS the choice for computer cluster environments!
