### ISSUE TITLE
Retirement of python2.7

### ISSUE THREAD

**Issue by markuskowa** [markuskowa/NixOS-QChem#236]
Since `numpy` has been removed in https://github.com/NixOS/nixpkgs/commit/0fa639e2aa3a53a8afbffedc62f7ab36c0aee581 from python2.7 the following packages can not be build anymore:
* `qchem.python2.pychemps2`
* `qchem.python2.pyquante`
* `qchem.sharc`

The last two seem to rely on python-2.7. We need to evaluate if this can be fixed with a reasonable amount of effort, or rather mark them as broken.

**Comment by sheepforce** [comment]
I guess Sharc is broken at this point beyond repair and simply going with 2to3 over it is likely to leave a complete mess. Sharc developers told us that they are porting to Python3 currently and rewrote some parts. Seems to have progressed well but is not complete yet. I think until then I would consider it broken.

**Comment by sheepforce** [comment]
Regarding chemps2: I would suggest to just build it python3 exclusive, which works flawlessly. I don't think some package uses it via Python2.

**Comment by markuskowa** [comment]
> Regarding chemps2: I would suggest to just build it python3 exclusive, which works flawlessly. I don't think some package uses it via Python2.

Then the solution is simple: I mark `sharc` and `pyquante` as broken and only build `pychemps2` on python-3. `pyquante` is even unmaintained in its current form.
