### ISSUE TITLE
Multiwfn Hash and Repo

### ISSUE THREAD

**Issue by sheepforce** [markuskowa/NixOS-QChem#239]
Currently the Multiwfn hash changes every week and the patches for CP2K and Multiwfn quickly outdate. I am thinking about forking it in a separate Git repository where a Pipeline automatically attempts an update every week. We could then point the derivation to this fork. It would also make patching easier. What is your opinion on this? The current situation is just super fragile.

**Comment by markuskowa** [comment]
> I am thinking about forking it in a separate Git repository where a Pipeline automatically attempts an update every week.

Yes, that sounds like a workable solution.
You could also write to the developer of Multiwfn. Maybe you can convince to place his code in a git repository or even to make a new release?

**Comment by sheepforce** [comment]
Alright, I will try the Git repo then :)

I've asked in the forum some time ago for a stable link to development versions and unfortunately the developer prefers the current model. :grimacing:
