### ISSUE TITLE
Python-2.7 retirement

### ISSUE THREAD

**Issue by markuskowa** [markuskowa/NixOS-QChem#241]
With https://github.com/NixOS/nixpkgs/pull/201859 python-2.7 has now been finally marked as insecure.

We now have a few packages that are affected by that change:
* [x] NWchem (working on it)
* [x] Molpro
* [x] mcdth (will try to bump to python-3 otherwise remove)
* [x] pysisyphus

CC @sheepforce

**Comment by sheepforce** [comment]
Pysisyphus shouldn't be a problem. I am not even sure where it would strictly require Python2. 

However, I am completely booked with finishing my thesis and will not be able to look at it for the next 1 or 2 weeks. I will fix it afterwards :)

**Comment by markuskowa** [comment]
@sheepforce nevermind, `pysisyphus` was an indirect failure.
