### ISSUE TITLE
How to define mpi as openmpi?

### ISSUE THREAD

**Issue by aolasz** [markuskowa/NixOS-QChem#25]
Thank you for NixOS-QChem. This was a deciding factor to reinstall our HPC cluster using nixos/nixops with slurm. (25 nodes, 1G ethernet, NFS)

I am learning nix(os) on the fly. I managed to install slurm-tools using NixOS-QChem as a nix channel. I have failed to install anything with mpi, however, as I have no clue how to define that openmpi should be used for mpi.

I have found your [PR](https://github.com/NixOS/nixpkgs/pull/108983) and a seemingly relevant discourse [thread](https://discourse.nixos.org/t/hpc-benchmark-with-different-mpi-implementations/9008), but still could not figure it out.

Please help me with a beginner oriented example and I will add a relevant section to [README.md](../blob/master/README.md).

**Comment by markuskowa** [comment]
Glad to see that Nix is picking up steam in the HPC community.

To build an application with MPI just put `mpi` in your `buildInputs`. It is set to `openmpi` by default in upstream nixpkgs. 
A relatively simple example is scalapack: https://github.com/NixOS/nixpkgs/blob/d600f006643e074c2ef1d72e462e218b647a096c/pkgs/development/libraries/science/math/scalapack/default.nix

Maybe you can elaborate what problems you had with your MPI installation?

**Comment by markuskowa** [comment]
Has this issue been resolved?

**Comment by aolasz** [comment]
Yes, this is solved. After a long suffering period I realized that it was a bug in 20.09, which caused an infinite recursion error when overriding mpi. I just did not assume the problem could be with nixos.
