### ISSUE TITLE
Molpro sha256

### ISSUE THREAD

**Issue by sheepforce** [markuskowa/NixOS-QChem#27]
Our Molpro archives have mismatching `sha256` hashes, even though they are exactly the same version. They seem to generate the archive , whenever you download it. This is a little bit annoying as it somehow breaks reproducability. Could we maybe make the Molpro `sha256` an option in `cfg.nix`?

**Comment by markuskowa** [comment]
Is that case for all versions?

**Comment by sheepforce** [comment]
Good question. I cannot verify it for all. It seems at least to be the case since they switched their license model (2 years ago I think?).

**Comment by markuskowa** [comment]
I'll try to get to bottom of it.

**Comment by sheepforce** [comment]
False alarm, our admin has repacked all archives and this has changed time stamps ...
