### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by juselius** [markuskowa/NixOS-QChem#3]
Love what you have done, keep up the good work! 

I have been using Nix (and home-manager) on a CentOS cluster for a few years now, and it's _the_ way to go. No question about it. Environment modules, lmod and EasyBuild are the wrong tools for the wrong problem. On our next cluster I will go all in, and try to get Infiniband and BeeGFS to work under NixOS. My hope is to manage the whole cluster using PXE with a custom, headless NixOS install image and the rest with NixOps and Cachix.

**Comment by markuskowa** [comment]
Thank you! I actually run a whole cluster on NixOS with slurm. It works like a charm.

A word of warning regarding BeeGFS. It is a great filesystem but, like lustre, is developed on traditional Linux distributions. We had it integrated in NixOS (see here https://github.com/NixOS/nixpkgs/pull/33157) but removed it  (https://github.com/NixOS/nixpkgs/pull/74053). I had it running for a while on my cluster. However, I could not get it to run stable. Every few days/weeks the meta data daemon would hang and freeze the whole filesystem.

**Comment by juselius** [comment]
Interesting! Are you using NixOps to manage the cluster? I use NixOps for a couple of Kubernetes clusters, and it's brilliant! 

A few questions: Are you running on Infiniband? If so, do you have nix-expressions for the setup? When using BeeGFS, I guess you were running the whole storage solution on NixOS? We are getting a turn-key BeeGFS solution, so I only need to get the BeeGFS client modules to work (with Infiniband support). Do you have any experience with that?

**Comment by markuskowa** [comment]
I do use NixOps to manage the cluster and it gets job done well but I consider switching to [morph](https://github.com/DBCDK/morph) as it is stateless and bit more simplistic than NixOps (NixOps shines with it's cloud backends, which I don't really need in a bare metal environment).

I do not run Infiniband on my cluster but some of my colleagues do (here is a [minimalist module](https://github.com/markuskowa/nix-system/blob/master/modules/infiniband.nix)). I eventually decided to run the setup on 10G ethernet for budget reasons. I still do run everything on NixOS (login nodes, 14 compute nodes, 3 storage servers with NFS/ZFS, 1 backup server with borg backup). 

A turn key solution with only BeeGFS clients on NixOS may run better. I had only problems with the server side components. The last version of BeeGFS (see link above) that was in NixOS had Infiniband support compiled in (although I was never able to test it). The main challenge with reactivating the NixOS integration is that it requires an upgrade to the latest BeeGFS version. This was the reason (together with the stability issues) why I dropped the package. Compiling BeeGFS on NixOS is not an easy task as it comes with only a bunch of Makefiles that require a lot of manual patch work. However, if I am willing to help if you want give it try.

**Comment by juselius** [comment]
Thanks for the info! I had not heard of `morph` before, but it looks very nice. I'll give it a spin and see how it compares to NixOps. I had not noticed that Infiniband was already in the kernel! You should try to get your infiniband module into the mainline nixpkgs. 

Perhaps we can collaborate on getting the BeeGFS client support back into nixpkgs, when the time comes. I'll give it a try when the new system is in place, and let you know how it's going.

**Comment by billksun** [comment]
@juselius, sorry for resurrecting this issue, but I am also interested in running BeeGFS client utils on NixOS. In particular running `beegfs-ctl`. Have you made any progress since?

**Comment by juselius** [comment]
Hi @billksun, I have some semi-updated BeeGFS-client nix-modules for version 7.4.0. They are probably easy to upgrade to 7.4.3. I have not used BeeGFS for a while now. I can share the nix-code with you if you like.

**Comment by billksun** [comment]
@juselius, that would be a massive help! Thanks!

**Comment by juselius** [comment]
@billksun I created a gist with my latest updates to @markuskowa original wotk: https://gist.github.com/juselius/7c1584c75530bc85cec31c3d13156a75
