### ISSUE TITLE
Sharc v21

### ISSUE THREAD

**Issue by ziechys** [markuskowa/NixOS-QChem#47]
Hiho, 

for sharcV21 two issues arose: 

1) 
The variable $SHARC pointing towards the relevant python skripts has to be set. 

2) 
Sharc does not work with Openmolcas 21. 
In general, it seems to only be designed to work for versions 18.x 
There are two options:
i) pair it with Openmolcas 18.x
ii) allow read-write manipulations of the SHARC_MOLCAS.py to circumvent this restriction manually. However, it has to be seen if this would cause actual problems with Sharc. 

Thanks a lot

**Comment by sheepforce** [comment]
Hey @ziechys ,

1. In Nix the executables, that need those environments are often wrapped in a shell script, that sets their environments. For SHARC this happens [here](https://github.com/markuskowa/NixOS-QChem/blob/e7b984ce9875f89d24ba10de33f7f9ca8dc0f0c1/pkgs/apps/sharc/21.nix#L72). Therefore `$SHARC` is usually not set in a `nix-shell -p sharcV21` but implicitly present for the executables of those packages. If you require this to be explicitly present in the `nix-shell`, you could use `shellHook = "export SHARC=${sharcV21}/bin"` in `mkShell`. If you get an error regarding the `$SHARC` variable, could you post it here? 
2. I've added OpenMolcas 18.09 in [this branch](https://github.com/sheepforce/NixOS-QChem/tree/sharc). Could you try with this branch and report back, if this works? :slightly_smiling_face: 

If this solves your issue, I will open a PR.

**Comment by markuskowa** [comment]
I haven't looked at it but do you have an idea how much work it would be to patch SHARC for newer molcas version?

**Comment by ziechys** [comment]
Thanks @sheepforce 

1)  yes the problem is that the Sharc internal scripts use $SHARC all the time and crash if it is not defined.  I added a shellHook to my shell.nix. It gives the error:

> error: while evaluating the attribute 'shellHook' of the derivation 'nix-shell' at /nix/store/zqag3s814ddr8nq370qigiasrm0g25xw-nixpks-unstable/pkgs/stdenv/generic/make-derivation.nix:201:11:
undefined variable 'sharcV21' at /user/ziems/Software/NixOS-QChem/shell.nix:9:108

2) I get the following error during installation:
> CMake`` Error at CMakeLists.txt:1348 (message):
  OpenBLAS library not found, please check that the OPENBLASROOT variable is
  set and points to a valid OpenBLAS installation directory.
-- Configuring incomplete, errors occurred!
See also "/build/source/build/CMakeFiles/CMakeOutput.log".
builder for '/nix/store/aznq5bjiyp32qjhxwflss6d9x519x7ry-openmolcas-18.09-02.09.2018.drv' failed with exit code 1
cannot build derivation '/nix/store/daiv0slmbrfx44i3mqlq8mwvpyfbp41f-sharc-2.1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/daiv0slmbrfx44i3mqlq8mwvpyfbp41f-sharc-2.1.drv' failed

@markuskowa  It would be nice to use the newest version of OpenMolcas. As written above one could just alter SHARC_MOLCAS.py (if Nix allows) to allow the newer version and then see/test if Sharc can run with it. I think, it might not be a problem as long as OpenMolcas did not change some output structure.

**Comment by sheepforce** [comment]
Ah sorry for the mistakes. I've just tested with MKL, not with OpenBLAS. Please try again with the current commit from my `sharc` branch. Regarding the `nix-shell` it should also have been `shellHook = "export SHARC=${qchem.sharcV21}/bin"`. Sorry!

We cannot make something in the nix-store writable, but I've tried with a recent OpenMolcas version and did not encounter an issue so far. If you want to test this out, please try my [`sharc-newmolcas`](https://github.com/sheepforce/NixOS-QChem/tree/sharc-newmolcas) branch. [This is the relevant patch](https://github.com/sheepforce/NixOS-QChem/commit/9ec6cebf478c3572bb4e5a5bfad37c5c56859db7#diff-9dd5933b0a3e7fb0b15d398a164119479042c56809ac47f819992dbd81526df7).

Regarding the `$SHARC` variable: SHARC seems to work fine, as far as I can tell so far. If you follow the tutorial, where they use something like `$SHARC/molcas_input.py`, this is just used as they never set a `$PATH` correctly during their SHARC installation. You can ignore the `$SHARC/` prefix in front of the commands and just execute e.g. `molcas_input.py`.

**Comment by ziechys** [comment]
Thanks a lot @sheepforce 

I am using the `sharc-newmolcas` branch now. So far all seems to work. 

I need the shellHook not for executable like `molcas_input.py`, but because Sharc itself creates scripts that use $SHARC as variable hard-coded in it. This then leads to errors. The shellHook solution works, tho.
