### ISSUE TITLE
Add to NUR?

### ISSUE THREAD

**Issue by Mic92** [markuskowa/NixOS-QChem#5]
This might be useful for other folks as well: https://github.com/nix-community/NUR

NUR helps because of easier setup and our search.

**Comment by markuskowa** [comment]
Why not. Would that require a change in my top level directory structure?

**Comment by Mic92** [comment]
To get packages appearing in the search we would need a package set rather than an overlay.
However it would be possible to expose just the overlay itself like this:

https://github.com/nix-community/NUR#nixos-modules-overlays-and-library-function-support

You can create an alternative wrapper file that is only used for nur to achieve this: https://github.com/nix-community/NUR/blob/master/repos.json#L182

**Comment by markuskowa** [comment]
I'll keep it in mind. making it available via NUR could be good. The wrapper seems to be the best solution, since the overlay is part of a production system.
