### ISSUE TITLE
AVX512 in openblas is broken

### ISSUE THREAD

**Issue by markuskowa** [markuskowa/NixOS-QChem#52]
## Problem
After re-building all packages on Xeon Scalable Bronze, which has AVX512, I noticed that multiple packages, which are linked against openblas, do not pass their tests anymore or their test never finish.
The affected packages that I have observed are:
* molcas (`tests.molcas`)
* chemps2 (see also https://github.com/markuskowa/NixOS-QChem/issues/40)
* pyscf (see also https://github.com/markuskowa/NixOS-QChem/issues/29)
* octave (the full feature override in the overlay)
* nwchem (`tests.nwchem`)

## Solution
Possible workarounds are:
* set `OPENBLAS_CORETYPE` at runtime (`HASWELL`, `ATHLON` work, `SKYLAKEX` fails). Needs to be set in every derivation!
* override openblas and add `NO_AVX512=1` to `makeFlags`.

openblas 0.3.15 is already in staging (need to check if the problem still exists here).

## Branches affected
* NixOS-QChem master
* nixpkgs unstable, release-21.05 (as of writing this issue)

cc @sheepforce 

EDIT: `openblas-0.3.15`, which is staging does not seem to solve any of the problems.

**Comment by sheepforce** [comment]
Ah to bad that this affects even more packages. At the moment I am setting `OPENBLAS_CORETYPE=HASWELL` in the `preOverlay` and this works, but I guess `NO_AVX512=1` is more specific. Do we know if this problem also exists upstream at OpenBLAS itself, outside of NixPkgs?

**Comment by markuskowa** [comment]
I have not found any other reports of bugs so far. Neither Debian nor Fedora turn it off in their builds. I am a bit puzzled that no one else has discovered this problem.
It could be that we have a fringe case here: AVX512 is not very widely used (only in more expensive CPUs) combined with the fact that HPC applications tend to use MKL more frequently than openblas.

**Comment by sheepforce** [comment]
Hm, possibly we should let the OpenBLAS developers know?

Now that you've merged #54 we can maybe check if the problems in CP2K, XTB and Bagel with BLAS can be solved. I've built them all on my AVX512 machine an it is very well possible, that I've ran into such problems there.

**Comment by markuskowa** [comment]
> Hm, possibly we should let the OpenBLAS developers know?

Yes that would be good, but this bug report will be very unspecific from the point of the developers: we have no idea which routines are affected (I am not sure yet how to write that but report).

> Now that you've merged #54 we can maybe check if the problems in CP2K, XTB and Bagel with BLAS can be solved. I've built them all on my AVX512 machine an it is very well possible, that I've ran into such problems there.

Yes, that would be nice. For Bagel it may not work, since that always had trouble with openblas.

**Comment by sheepforce** [comment]
Now that the fix is available upstream and those packages build with OpenBlas, can we close this?
