### ISSUE TITLE
Packages to be moved to upstream nixpkgs

### ISSUE THREAD

**Issue by markuskowa** [markuskowa/NixOS-QChem#56]
This is a list to keep track of packages that are either good enough to be submitted to upstream nixpkgs or can be easily brought into shape for upstream nixpkgs.

* [x] `f2c`
* [x] `cp2k`, may require a little bit of cleanup
* [x] `dkh`
* [x] `ergoscf`
* [x] `i-Pi`
* [x] `libint`
* [x] `libvori`
* [x] `pcmsolver`
* [x] `pyscf`
* [x] `qcelemental`
* [x] `qcengine`
* [x] `mvapich`
* [x] `xcfun`

**Comment by sheepforce** [comment]
As discussed some time ago I've opened a PR against NixPkgs to be added as a maintainer and would take of a few of those. See https://github.com/NixOS/nixpkgs/pull/124370

**Comment by markuskowa** [comment]
* NWchem is stable but the build system is too messy. I rather keep it local.
* XTB takes proprietary packages as inputs, making it less suitable for nixpkgs.
* GPAW could be doable but also requires `libvdwxc`.

**Comment by sheepforce** [comment]
CP2K is running just fine now, I suppose. I would be fine with maintaining it upstream, if that's OK for you (I also use it regularly)? Upstream there is no bats test. Is it OK for upstream to simply inline them as a installCheckPhase?

**Comment by markuskowa** [comment]
> CP2K is running just fine now, I suppose. I would be fine with maintaining it in NixOS/nixpkgs, if that's OK for you (I also use it regularly)? 

Yes, we can do that but `libvori` is missing upstream. We should PR that one first.

> Upstream there is no bats test. Is it OK for upstream to simply inline them as a installCheckPhase?

That is OK. We just keep the bats tests here. Expensive install checks are not so welcome upstream anyway since Hydra is already very busy. The advantage of having it here is that they are run local hardware (at least from my perspective).

**Comment by sheepforce** [comment]
I was starting to port CP2K to nixpkgs and just noticed that also libint is missing. Would you like to bring it to nixpkgs or should I take care of this?

**Comment by sheepforce** [comment]
> I was starting to port CP2K to nixpkgs and just noticed that also libint is missing. Would you like to bring it to nixpkgs or should I take care of this?

I have a branch [here](https://github.com/sheepforce/nixpkgs/tree/libint).

**Comment by markuskowa** [comment]
I will take a look `libint`. That one requires some cleanup.

**Comment by sheepforce** [comment]
Also just saw that fftw is built without Fortran bindings upstream. I guess enabling this would cause many rebuilds?

**Comment by markuskowa** [comment]
I am closing this issue, since the list is completed now. 
We have managed to mature quite a lot of packages for the inclusion into nixpks :tada:
